# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: BasantPandey.CmdWarden
PackageVersion: 0.8.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cw.exe
  PortableCommandAlias: cw
- RelativeFilePath: cmdwarden.exe
  PortableCommandAlias: cmdwarden
InstallModes:
- silent
UpgradeBehavior: install
Commands:
- cw
- cmdwarden
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/BasantPandey/CmdWarden/releases/download/v0.8.0/CmdWarden.0.8.0-win-x64.zip
  InstallerSha256: 8F787DCFBB70B5F7CEA5396114D5C748589F0356DC2C6F20F3EEC138283C65D4
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2026-09-27
